#!/usr/bin/env python3
"""Keeps the settings window's Localizable.strings in sync with the Swift sources.

  scripts/localization.py          check that every language has every key (CI)
  scripts/localization.py --write  regenerate en.lproj from the sources, then check

Keys are the English texts used in SwiftUI calls (Text("…"), Button("…"), …) and
String(localized: "…"). Interpolations become format specifiers like Xcode does:
Int values (%lld) and everything else (%@).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ROOT / "settings" / "Sources"
RESOURCES = ROOT / "settings" / "Resources"
LANGUAGES = ["en", "de"]

CALLS = (
    r"Text|Button|Toggle|Label|Section|LabeledContent|Picker|TextField|SecureField|Stepper|Menu|"
    r"Window|confirmationDialog|\.help|\.navigationTitle"
)
LITERAL = r'"((?:[^"\\]|\\.)*)"'
PATTERNS = [
    re.compile(rf"(?:{CALLS})\(\s*{LITERAL}"),
    re.compile(rf"(?:title|footnote|namePrompt|valuePrompt|addLabel):\s*{LITERAL}"),
    re.compile(rf"String\(localized:\s*{LITERAL}"),
]
INT_HINTS = ("Secs", "count", "Count")


def swift_to_key(literal: str) -> str:
    def interpolation(m: re.Match) -> str:
        return "%lld" if any(h in m.group(1) for h in INT_HINTS) else "%@"

    key = re.sub(r"\\\(([^()]*(?:\([^()]*\))?[^()]*)\)", interpolation, literal)
    return key.replace('\\"', '"').replace("\\\\", "\\")


def source_keys() -> set[str]:
    keys = set()
    for path in sorted(SOURCES.glob("*.swift")):
        for line in path.read_text().splitlines():
            if "verbatim:" in line:
                line = re.sub(rf"verbatim:\s*{LITERAL}", "", line)
            for pattern in PATTERNS:
                for m in pattern.finditer(line):
                    if m.group(1):
                        keys.add(swift_to_key(m.group(1)))
    return keys


def escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def unescape(s: str) -> str:
    return re.sub(r"\\(.)", lambda m: {"n": "\n"}.get(m.group(1), m.group(1)), s)


ENTRY = re.compile(r'^"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)";\s*$')


def read_strings(path: Path) -> dict[str, str]:
    entries = {}
    for n, line in enumerate(path.read_text().splitlines(), 1):
        line = line.strip()
        if not line or line.startswith("/*") or line.startswith("//"):
            continue
        m = ENTRY.match(line)
        if not m:
            sys.exit(f"{path}:{n}: cannot parse: {line}")
        entries[unescape(m.group(1))] = unescape(m.group(2))
    return entries


def specifiers(s: str) -> list[str]:
    return sorted(re.findall(r"%(?:lld|@|d)", s))


def main() -> None:
    keys = source_keys()
    if "--write" in sys.argv:
        out = RESOURCES / "en.lproj" / "Localizable.strings"
        out.parent.mkdir(parents=True, exist_ok=True)
        lines = ["/* Generated by scripts/localization.py --write. English is the source language. */", ""]
        lines += [f'"{escape(k)}" = "{escape(k)}";' for k in sorted(keys)]
        out.write_text("\n".join(lines) + "\n")

    ok = True
    for lang in LANGUAGES:
        path = RESOURCES / f"{lang}.lproj" / "Localizable.strings"
        if not path.exists():
            print(f"{lang}: missing {path.relative_to(ROOT)}")
            ok = False
            continue
        entries = read_strings(path)
        for k in sorted(keys - entries.keys()):
            print(f"{lang}: missing translation: {k!r}")
            ok = False
        for k in sorted(entries.keys() - keys):
            print(f"{lang}: unused key: {k!r}")
            ok = False
        for k in sorted(keys & entries.keys()):
            if specifiers(k) != specifiers(entries[k]):
                print(f"{lang}: placeholders differ: {k!r} -> {entries[k]!r}")
                ok = False
    print(f"{len(keys)} keys, {'ok' if ok else 'PROBLEMS'}")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
